export const colorList = [
  'black',
  'grey',
  'darkgrey',
  'lightgrey',
  'white',
  'lightyellow',
  'yellow',
  'orange',
  'darkorange',
  'red',
  'darkred',
  'maroon',
  'brown',
  'pink',
  'lightgreen',
  'green',
  'darkgreen',
  'teal',
  'darkblue',
  'blue',
  'lightblue',
  'skyblue',
  'cyan',
  'violet',
  'purple',
];

export const newTextLayer = {
  type: 'text',
  content: {
    value: 'Editable Text.',
    color: 'white',
    stroke: 5,
    strokeColor: 'black',
    shadow: true,
    size: 20,
  },
  x: 0,
  y: 0,
};
